# Anti-Gravity Skills and Configuration Auto-Backup Script (backup_skills.ps1)
# Execution: PowerShell.exe -ExecutionPolicy Bypass -File .\backup_skills.ps1

$ErrorActionPreference = "SilentlyContinue"

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "💾 Anti-Gravity Skills & Configs One-Click Backup" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# Construct G:\我的雲端硬碟\GOOGLE ANGET dynamically to avoid encoding issues in PowerShell 5.1
$gdriveName = [string][char]0x6211 + [char]0x7684 + [char]0x96f2 + [char]0x7aef + [char]0x786c + [char]0x789f
$gdrivePath = "G:\$gdriveName\GOOGLE ANGET"

if (-not (Test-Path $gdrivePath)) {
    Write-Host "Error: Could not find Google Drive project directory at $gdrivePath!" -ForegroundColor Red
    Write-Host "Please ensure Google Drive client is installed and running." -ForegroundColor Yellow
    Read-Host "Press Enter to exit..."
    exit 1
}

$backupPath = Join-Path $gdrivePath "backup"
if (-not (Test-Path $backupPath)) {
    New-Item -ItemType Directory -Path $backupPath -Force | Out-Null
}

$userProfile = $env:USERPROFILE
$localAGDir = Join-Path $userProfile ".gemini\antigravity"
$localConfigDir = Join-Path $userProfile ".gemini\config"
$workspaceSkillsDir = "C:\GOOGLE ANGET\skills"

Write-Host "Target backup directory: $backupPath" -ForegroundColor Gray

# 2. Backup Global Config and Permissions (C:\Users\<User>\.gemini\config)
Write-Host "Backing up global config folder..." -ForegroundColor Yellow
if (Test-Path $localConfigDir) {
    $targetConfig = Join-Path $backupPath "config"
    Copy-Item -Path $localConfigDir -Destination $targetConfig -Recurse -Force
    Write-Host "✅ Global config backed up successfully!" -ForegroundColor Green
} else {
    Write-Host "Warning: Global config folder not found." -ForegroundColor Gray
}

# 3. Backup Antigravity prompt-skills and user settings
Write-Host "Backing up Antigravity custom skills and user settings..." -ForegroundColor Yellow
$agSkillsSrc = Join-Path $localAGDir "skills"
$agSettingsSrc = Join-Path $localAGDir "user_settings.pb"

if (Test-Path $agSkillsSrc) {
    $targetAGSkills = Join-Path $backupPath "antigravity\skills"
    Copy-Item -Path $agSkillsSrc -Destination $targetAGSkills -Recurse -Force
    Write-Host "✅ Custom skills backed up successfully!" -ForegroundColor Green
}
if (Test-Path $agSettingsSrc) {
    $targetAGSettings = Join-Path $backupPath "antigravity\user_settings.pb"
    Copy-Item -Path $agSettingsSrc -Destination $targetAGSettings -Force
    Write-Host "✅ User settings backed up successfully!" -ForegroundColor Green
}

# 4. Backup Workspace Skills (C:\GOOGLE ANGET\skills)
Write-Host "Backing up local workspace skills..." -ForegroundColor Yellow
if (Test-Path $workspaceSkillsDir) {
    $targetWorkspaceSkills = Join-Path $backupPath "workspace_skills"
    Copy-Item -Path $workspaceSkillsDir -Destination $targetWorkspaceSkills -Recurse -Force
    Write-Host "✅ Local workspace skills backed up successfully!" -ForegroundColor Green
}

# 5. Write README.md in backup folder
Write-Host "Updating backup README.md..." -ForegroundColor Yellow
$timeStr = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
$readmeContent = @(
  "# GOOGLE ANGET - AI Agent Skills Backup Folder",
  "",
  "This folder was automatically generated by the backup script on $timeStr.",
  "",
  "## Folder Structure and Restore Target Mapping:",
  "1. **config/**",
  "   - Target path on new computer: 'C:\Users\<Username>\.gemini\config\'",
  "   - Contains config.json and mcp_config.json.",
  "2. **antigravity/skills/**",
  "   - Target path on new computer: 'C:\Users\<Username>\.gemini\antigravity\skills\'",
  "   - Contains prompt-based customizations.",
  "3. **antigravity/user_settings.pb**",
  "   - Target path on new computer: 'C:\Users\<Username>\.gemini\antigravity\user_settings.pb'",
  "4. **workspace_skills/**",
  "   - Target path on new computer: 'C:\GOOGLE ANGET\skills\'",
  "",
  "---",
  "*Last Backup Time: $timeStr*"
) -join "`r`n"

$readmeContent | Out-File -FilePath (Join-Path $backupPath "README.md") -Encoding utf8 -Force
Write-Host "✅ README.md created in backup directory!" -ForegroundColor Green

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "🎉 Skills & configurations successfully backed up!" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Read-Host "Press Enter to exit..."
